# Generated by Django 4.2.16 on 2024-11-29 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(choices=[('male', 'Мужской'), ('female', 'Женский')], max_length=10)),
                ('satisfaction', models.CharField(choices=[('very_satisfied', 'Очень доволен'), ('satisfied', 'Доволен'), ('neutral', 'Нейтрально'), ('dissatisfied', 'Недоволен'), ('very_dissatisfied', 'Очень недоволен')], max_length=20)),
                ('comments', models.TextField()),
                ('subscribe', models.BooleanField(default=False)),
            ],
        ),
    ]
