# Generated by Django 4.2.16 on 2024-12-02 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_blogpost_author_alter_blogpost_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feedback',
            options={'verbose_name': 'Обратная связь', 'verbose_name_plural': 'Обратная связь'},
        ),
    ]
